/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiSenseRouteImport } from './routes/api/sense'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSenseRoute = ApiSenseRouteImport.update({
  id: '/api/sense',
  path: '/api/sense',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/sense': typeof ApiSenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/sense': typeof ApiSenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/sense': typeof ApiSenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/live' | '/api/sense'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/live' | '/api/sense'
  id: '__root__' | '/' | '/api/live' | '/api/sense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiSenseRoute: typeof ApiSenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sense': {
      id: '/api/sense'
      path: '/api/sense'
      fullPath: '/api/sense'
      preLoaderRoute: typeof ApiSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiSenseRoute: ApiSenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
